name: normacore

services:
  api:
    ports:
      - "8000:8000"

  qdrant:
    ports:
      - "6333:6333"

  ollama-cpu:
    ports:
      - "11434:11434"

  ollama-gpu-docker:
    ports:
      - "11434:11434"

  ollama-gpu-podman:
    ports:
      - "11434:11434"
